import fs from "node:fs";
import path from "node:path";
import puppeteer from "puppeteer-core";
const LAB = "D:/zh-ui-lab";
const key = /LITELLM_MASTER_KEY:\s*(\S+)/.exec(fs.readFileSync(path.join(LAB, "overlay-ui.yml"), "utf8"))[1];
const b = await puppeteer.launch({ executablePath: "C:\Program Files\Google\Chrome\Application\chrome.exe", headless: "new", args: ["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width: 1680, height: 1000 });
const errs = [];
p.on("pageerror", (e) => errs.push(String(e.message).slice(0, 200)));
p.on("console", (m) => { if (m.type() === "error") errs.push("console:" + m.text().slice(0, 160)); });
await p.goto("http://localhost:4000/ui/login/", { waitUntil: "networkidle2", timeout: 60000 });
await p.waitForSelector('input[name="username"]', { timeout: 20000 });
await p.type('input[name="username"]', "admin");
await p.type('input[name="password"]', key);
await Promise.all([p.waitForNavigation({ waitUntil: "networkidle2", timeout: 60000 }).catch(() => {}), p.click('button[type="submit"]')]);
await new Promise((r) => setTimeout(r, 3000));
await p.goto("http://localhost:4000/ui/api-keys/", { waitUntil: "networkidle2", timeout: 60000 });
await new Promise((r) => setTimeout(r, 4000));
await p.screenshot({ path: path.join(LAB, "shots", "keys-after-guardfix.png"), fullPage: false });
console.log("URL", p.url());
console.log("errors", JSON.stringify(errs.slice(0, 6), null, 1));
await b.close();
